env:
  global:
    - CC_TEST_REPORTER_ID=4d0e520e3acf909d719189c558e58da8dfda621228c29fac1d2a5f404fd80a0e
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install -r requirements/dev.txt
  - pip install flake8
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - py.test dead_test.py --cov=deadWeb
  - flake8 deadWeb
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
