language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install -r requirements/dev.txt
  - pip install flake8
script:
  - py.test dead_test.py --cov=deadWeb
  - coverage html -d /tmp/coverage
  - flake8 deadWeb
